
CREATE TABLE subscribers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    subscription_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);